# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f341da18f4e158c5265a7fbf126808eba24f180082febbe2fb1a2707805c6cc70f75433757980409da2dc23fa734b4e2f27ebcb5a88a2e83072fdbe661770612

test:
  secret_key_base: 5d64d9ab5afc90cc7e087cc5571e0c8582fe832704fa54aa80fd75f9da9bae38a28bbb7936f785a4cca167d6da460d6a192ca89d8aa0e2126ce3b195fb96510d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
